// Seed data: 20 products per category, grouped by category name.
export const productsByCategory = {
  Ceramics: [
    {
      name: 'Handcrafted Terracotta Chai Kulhar Set',
      description: 'Set of 6 unglazed natural red clay cups. Hand-thrown on traditional wheels in Khurja, cooling chai naturally and imparting an earthy aroma.',
      price: 649,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/terracotta,cup?lock=1',
    },
    {
      name: 'Jaipur Blue Pottery Floral Vase',
      description: 'Hand-painted cobalt and turquoise vase made from quartz dough and fired at low heat, in the classic Jaipur blue pottery tradition.',
      price: 1299,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/blue,vase?lock=2',
    },
    {
      name: 'Khurja Ceramic Dinner Plate Set of 4',
      description: 'Glazed 10-inch dinner plates with a hand-brushed floral rim. Microwave and dishwasher safe, made in the potteries of Khurja.',
      price: 1899,
      stock: 25,
      imageUrl: 'https://loremflickr.com/800/800/ceramic,plates?lock=3',
    },
    {
      name: 'Hand-Painted Ceramic Soup Bowl Set',
      description: 'Set of 4 deep bowls with a smooth white glaze and hand-drawn blue motifs. Holds about 350 ml each.',
      price: 999,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/ceramic,bowl?lock=4',
    },
    {
      name: 'Speckled Stoneware Coffee Mug',
      description: 'Wheel-thrown stoneware mug with a speckled oatmeal glaze and a comfortable thumb-rest handle. Holds 300 ml.',
      price: 449,
      stock: 80,
      imageUrl: 'https://loremflickr.com/800/800/coffee,mug?lock=5',
    },
    {
      name: 'Terracotta Planter with Saucer',
      description: 'Breathable clay planter with a matching saucer. Ideal for succulents and herbs, with a drainage hole and a natural matte finish.',
      price: 549,
      stock: 60,
      imageUrl: 'https://loremflickr.com/800/800/terracotta,planter?lock=6',
    },
    {
      name: 'Celadon Green Ceramic Tea Set',
      description: 'One teapot and four handleless cups in a soft celadon glaze. The pot has a built-in strainer and holds 600 ml.',
      price: 2499,
      stock: 18,
      imageUrl: 'https://loremflickr.com/800/800/teapot,ceramic?lock=7',
    },
    {
      name: 'Handmade Ceramic Butter Dish with Lid',
      description: 'Covered stoneware butter dish with a smooth glaze, keeping butter fresh and spreadable on the counter.',
      price: 699,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/butter,dish?lock=8',
    },
    {
      name: 'Glazed Ceramic Incense Holder',
      description: 'Compact boat-shaped incense holder with a raised rest, glazed in a deep ocean blue. Catches ash neatly.',
      price: 349,
      stock: 90,
      imageUrl: 'https://loremflickr.com/800/800/incense,ceramic?lock=9',
    },
    {
      name: 'Longpi Black Pottery Serving Bowl',
      description: 'Hand-coiled black pottery bowl in the tradition of the Tangkhul Naga artisans of Manipur, burnished for a natural sheen.',
      price: 1599,
      stock: 20,
      imageUrl: 'https://loremflickr.com/800/800/black,pottery?lock=10',
    },
    {
      name: 'Blue Pottery Tile Coaster Set of 6',
      description: 'Six hand-painted square coasters with cork backing, protecting tables from heat and rings.',
      price: 799,
      stock: 50,
      imageUrl: 'https://loremflickr.com/800/800/coaster,tile?lock=11',
    },
    {
      name: 'Ceramic Aroma Oil Burner',
      description: 'Two-piece ceramic burner with a tea-light chamber on the bottom and an oil dish on top. Diffuses essential oils gently.',
      price: 899,
      stock: 28,
      imageUrl: 'https://loremflickr.com/800/800/aroma,burner?lock=12',
    },
    {
      name: 'Hand-Thrown Stoneware Salad Bowl',
      description: 'Wide 12-inch stoneware bowl with a reactive glaze, so no two pieces look exactly alike. Sturdy enough for daily use.',
      price: 1499,
      stock: 22,
      imageUrl: 'https://loremflickr.com/800/800/salad,bowl?lock=13',
    },
    {
      name: 'Ceramic Spoon Rest',
      description: 'Curved glazed spoon rest that keeps drips off the stove. Easy to wipe clean and dishwasher safe.',
      price: 299,
      stock: 100,
      imageUrl: 'https://loremflickr.com/800/800/spoon,ceramic?lock=14',
    },
    {
      name: 'Terracotta Matka Water Bottle',
      description: 'Unglazed clay bottle with a wooden cap that naturally cools water through evaporation. Holds 1 litre.',
      price: 599,
      stock: 55,
      imageUrl: 'https://loremflickr.com/800/800/clay,bottle?lock=15',
    },
    {
      name: 'Ceramic Salt and Pepper Shaker Pair',
      description: 'Matching glazed shakers with cork stoppers and hand-pierced tops. Compact and easy to refill.',
      price: 549,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/salt,shaker?lock=16',
    },
    {
      name: 'Traditional Ceramic Barni Pickle Jar',
      description: 'White and blue glazed jar with a wooden lid, the classic Indian barni used for storing pickles and preserves.',
      price: 899,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/pickle,jar?lock=17',
    },
    {
      name: 'Glazed Ceramic Wall Plate Set of 3',
      description: 'Three decorative plates in graduated sizes with a sturdy hanging loop on the back, painted with botanical designs.',
      price: 1799,
      stock: 20,
      imageUrl: 'https://loremflickr.com/800/800/decorative,plate?lock=18',
    },
    {
      name: 'Ceramic Bud Vase Trio',
      description: 'Three small bud vases in different shapes and complementary glazes, perfect for single stems and dried flowers.',
      price: 999,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/bud,vase?lock=19',
    },
    {
      name: 'Handmade Ceramic Cake Stand',
      description: 'Footed cake stand with a smooth white glaze and a lightly scalloped edge, sized for a 9-inch cake.',
      price: 1899,
      stock: 15,
      imageUrl: 'https://loremflickr.com/800/800/cake,stand?lock=20',
    },
  ],
  Textiles: [
    {
      name: 'Sanganeri Block-Printed Cotton Bedsheet',
      description: 'Double bedsheet with two pillow covers, printed by hand with carved wooden blocks in Sanganer using vegetable-based dyes.',
      price: 1799,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/bedsheet,cotton?lock=21',
    },
    {
      name: 'Handwoven Khadi Cotton Throw',
      description: 'Soft, breathable throw woven on a handloom from hand-spun khadi cotton. Light enough for summer evenings.',
      price: 1299,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/cotton,throw?lock=22',
    },
    {
      name: 'Ikat Cushion Cover Set of 2',
      description: 'Two 16-inch cushion covers woven in traditional ikat, where the yarn is resist-dyed before weaving.',
      price: 899,
      stock: 60,
      imageUrl: 'https://loremflickr.com/800/800/ikat,cushion?lock=23',
    },
    {
      name: 'Kantha Stitch Reversible Quilt',
      description: 'Layered cotton quilt with running-stitch kantha embroidery, reversible with a different pattern on each side.',
      price: 3499,
      stock: 15,
      imageUrl: 'https://loremflickr.com/800/800/kantha,quilt?lock=24',
    },
    {
      name: 'Handloom Cotton Table Runner',
      description: 'Six-seater table runner with a woven border, made on a pit loom by weavers in West Bengal.',
      price: 749,
      stock: 50,
      imageUrl: 'https://loremflickr.com/800/800/table,runner?lock=25',
    },
    {
      name: 'Hand-Embroidered Kashmiri Wool Stole',
      description: 'Fine wool stole with delicate sozni-style needlework along the edges, warm yet lightweight.',
      price: 2999,
      stock: 18,
      imageUrl: 'https://loremflickr.com/800/800/wool,shawl?lock=26',
    },
    {
      name: 'Bandhani Silk Scarf',
      description: 'Tie-dyed silk scarf with the tiny dot patterns of Gujarati bandhani, each dot tied by hand before dyeing.',
      price: 1199,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/bandhani,scarf?lock=27',
    },
    {
      name: 'Indigo Shibori Cotton Napkins Set of 6',
      description: 'Cotton napkins folded, bound and dipped in natural indigo to create one-of-a-kind patterns.',
      price: 699,
      stock: 55,
      imageUrl: 'https://loremflickr.com/800/800/indigo,napkin?lock=28',
    },
    {
      name: 'Chanderi Cotton-Silk Saree',
      description: 'Sheer, lightweight saree from Chanderi with a woven zari border, known for its glossy texture.',
      price: 4299,
      stock: 12,
      imageUrl: 'https://loremflickr.com/800/800/saree,silk?lock=29',
    },
    {
      name: 'Handwoven Jute Doormat',
      description: 'Sturdy natural jute doormat with a braided edge, durable and naturally coarse for scraping shoes.',
      price: 499,
      stock: 70,
      imageUrl: 'https://loremflickr.com/800/800/jute,doormat?lock=30',
    },
    {
      name: 'Patchwork Ralli Throw',
      description: 'Colourful throw stitched from reclaimed fabric scraps in the ralli tradition, with hand-quilted lines.',
      price: 2799,
      stock: 14,
      imageUrl: 'https://loremflickr.com/800/800/patchwork,quilt?lock=31',
    },
    {
      name: 'Hand-Knotted Wool Rug 4x6 ft',
      description: 'Dense hand-knotted wool rug with a geometric pattern, made by carpet weavers in Uttar Pradesh.',
      price: 8999,
      stock: 6,
      imageUrl: 'https://loremflickr.com/800/800/wool,rug?lock=32',
    },
    {
      name: 'Dabu Mud-Resist Print Curtain Panel',
      description: 'Cotton curtain panel printed with the Dabu technique, where mud paste resists the dye to form earthy patterns.',
      price: 1599,
      stock: 25,
      imageUrl: 'https://loremflickr.com/800/800/cotton,curtain?lock=33',
    },
    {
      name: 'Cotton Macrame Wall Hanging',
      description: 'Hand-knotted macrame wall art on a driftwood dowel, made from soft unbleached cotton cord.',
      price: 999,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/macrame,wall?lock=34',
    },
    {
      name: 'Ajrakh Block-Printed Cotton Stole',
      description: 'Lightweight stole printed in deep indigo and madder red using the centuries-old Ajrakh resist technique.',
      price: 1399,
      stock: 28,
      imageUrl: 'https://loremflickr.com/800/800/ajrakh,stole?lock=35',
    },
    {
      name: 'Linen Kitchen Towel Set of 3',
      description: 'Highly absorbent linen towels that dry quickly and soften with every wash.',
      price: 599,
      stock: 60,
      imageUrl: 'https://loremflickr.com/800/800/linen,towel?lock=36',
    },
    {
      name: 'Handwoven Cotton Bath Towel Set',
      description: 'Two large bath towels and two hand towels, woven from long-staple cotton with a waffle texture.',
      price: 1499,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/bath,towel?lock=37',
    },
    {
      name: 'Phulkari Embroidered Cushion Cover',
      description: 'Silk-thread embroidery in the vibrant phulkari style from Punjab, worked on soft cotton.',
      price: 799,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/embroidered,cushion?lock=38',
    },
    {
      name: 'Handloom Tussar Silk Stole',
      description: 'Naturally textured tussar silk with a warm golden tone, woven by artisans in Bhagalpur.',
      price: 1899,
      stock: 20,
      imageUrl: 'https://loremflickr.com/800/800/tussar,silk?lock=39',
    },
    {
      name: 'Block-Printed Quilted Tote Bag',
      description: 'Roomy quilted cotton tote with inner pocket and zip, printed with traditional floral blocks.',
      price: 549,
      stock: 75,
      imageUrl: 'https://loremflickr.com/800/800/tote,bag?lock=40',
    },
  ],
  Apothecary: [
    {
      name: 'Cold-Pressed Coconut Hair Oil',
      description: 'Pure virgin coconut oil cold-pressed in small batches. Nourishes the scalp and adds shine, 200 ml glass bottle.',
      price: 349,
      stock: 80,
      imageUrl: 'https://loremflickr.com/800/800/coconut,oil?lock=41',
    },
    {
      name: 'Kumkumadi Tailam Face Serum 30ml',
      description: 'Ayurvedic facial oil blended with saffron, sandalwood and turmeric to brighten and even out skin tone.',
      price: 1199,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/face,serum?lock=42',
    },
    {
      name: 'Neem and Tulsi Herbal Soap Bar',
      description: 'Cold-process soap with neem and holy basil, gentle for oily and acne-prone skin. 100 g.',
      price: 149,
      stock: 150,
      imageUrl: 'https://loremflickr.com/800/800/herbal,soap?lock=43',
    },
    {
      name: 'Ashwagandha Root Powder 100g',
      description: 'Finely milled organic ashwagandha root powder, traditionally used to help the body manage stress.',
      price: 399,
      stock: 70,
      imageUrl: 'https://loremflickr.com/800/800/ashwagandha,powder?lock=44',
    },
    {
      name: 'Steam-Distilled Rose Water 200ml',
      description: 'Pure rose water with no added fragrance, used as a refreshing toner and mist.',
      price: 249,
      stock: 90,
      imageUrl: 'https://loremflickr.com/800/800/rose,water?lock=45',
    },
    {
      name: 'Turmeric and Sandalwood Face Pack',
      description: 'Fine herbal powder of turmeric, sandalwood and rose petals to be mixed with water or milk. 100 g.',
      price: 299,
      stock: 65,
      imageUrl: 'https://loremflickr.com/800/800/turmeric,powder?lock=46',
    },
    {
      name: 'Triphala Churna 100g',
      description: 'A classic blend of three fruits: amla, haritaki and bibhitaki, ground fresh and packed in an airtight tin.',
      price: 249,
      stock: 85,
      imageUrl: 'https://loremflickr.com/800/800/triphala,herbs?lock=47',
    },
    {
      name: 'Lavender Essential Oil 15ml',
      description: 'Undiluted lavender oil with a calming floral scent, packed in a UV-protective amber bottle with a dropper.',
      price: 499,
      stock: 50,
      imageUrl: 'https://loremflickr.com/800/800/lavender,oil?lock=48',
    },
    {
      name: 'Tulsi Ginger Herbal Tea Blend 50g',
      description: 'Loose-leaf blend of holy basil, ginger and cinnamon that makes about 25 comforting cups.',
      price: 299,
      stock: 100,
      imageUrl: 'https://loremflickr.com/800/800/herbal,tea?lock=49',
    },
    {
      name: 'Shea and Cocoa Body Butter 100g',
      description: 'Rich whipped butter for dry skin, made with unrefined shea and cocoa butter and sweet almond oil.',
      price: 599,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/body,butter?lock=50',
    },
    {
      name: 'Bhringraj Amla Hair Oil 200ml',
      description: 'Traditional herb-infused oil for scalp massage, slow-cooked with bhringraj, amla and hibiscus in a sesame base.',
      price: 449,
      stock: 60,
      imageUrl: 'https://loremflickr.com/800/800/hair,oil?lock=51',
    },
    {
      name: 'Aloe Vera and Cucumber Gel 150g',
      description: 'Light, non-sticky gel that soothes sun-exposed skin and doubles as a cooling face moisturiser.',
      price: 299,
      stock: 75,
      imageUrl: 'https://loremflickr.com/800/800/aloe,vera?lock=52',
    },
    {
      name: 'Activated Charcoal Cold-Process Soap',
      description: 'Deep-cleansing bar with bamboo charcoal and tea tree oil, handcrafted and cured for six weeks.',
      price: 199,
      stock: 100,
      imageUrl: 'https://loremflickr.com/800/800/charcoal,soap?lock=53',
    },
    {
      name: 'Chamomile Sleep Herbal Tea 40g',
      description: 'Soothing loose-leaf blend of chamomile, lemon balm and lavender for winding down in the evening.',
      price: 349,
      stock: 55,
      imageUrl: 'https://loremflickr.com/800/800/chamomile,tea?lock=54',
    },
    {
      name: 'Eucalyptus and Camphor Vapour Balm 25g',
      description: 'Pocket-size balm made with beeswax and essential oils, soothing when applied to the chest or temples.',
      price: 199,
      stock: 120,
      imageUrl: 'https://loremflickr.com/800/800/balm,tin?lock=55',
    },
    {
      name: 'Rose and Sandalwood Attar Roll-On 10ml',
      description: 'Alcohol-free traditional perfume oil made in Kannauj, with a long-lasting warm floral aroma.',
      price: 799,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/perfume,bottle?lock=56',
    },
    {
      name: 'Multani Mitti Clay Mask 100g',
      description: 'Pure fuller\'s earth that draws out excess oil and impurities. Mix with rose water for a quick mask.',
      price: 249,
      stock: 80,
      imageUrl: 'https://loremflickr.com/800/800/clay,mask?lock=57',
    },
    {
      name: 'Almond Oil Herbal Kajal',
      description: 'Handmade kohl with almond oil and castor oil, smooth to apply and free from harsh chemicals.',
      price: 229,
      stock: 90,
      imageUrl: 'https://loremflickr.com/800/800/kajal,eyeliner?lock=58',
    },
    {
      name: 'Lemongrass Massage Oil 100ml',
      description: 'Invigorating body oil blending sesame and lemongrass, used for warm, relaxing massages.',
      price: 449,
      stock: 50,
      imageUrl: 'https://loremflickr.com/800/800/massage,oil?lock=59',
    },
    {
      name: 'Dried Herb Potpourri Sachet Set of 3',
      description: 'Cotton sachets filled with dried lavender, rose petals and cloves to freshen drawers and wardrobes.',
      price: 349,
      stock: 65,
      imageUrl: 'https://loremflickr.com/800/800/potpourri,sachet?lock=60',
    },
  ],
  Kitchenware: [
    {
      name: 'Pre-Seasoned Cast Iron Kadhai 10-inch',
      description: 'Heavy, thick-walled kadhai that holds heat evenly, ideal for deep frying and slow curries. Pre-seasoned and ready to use.',
      price: 1899,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/cast,iron,pan?lock=61',
    },
    {
      name: 'Hand-Hammered Copper Water Jug',
      description: 'Pure copper jug with a hammered finish, traditionally used to store drinking water overnight. Holds 1.5 litres.',
      price: 1799,
      stock: 25,
      imageUrl: 'https://loremflickr.com/800/800/copper,jug?lock=62',
    },
    {
      name: 'Stainless Steel 3-Tier Tiffin Carrier',
      description: 'Leak-resistant stacked containers with a clip-on handle, perfect for carrying a full meal to work.',
      price: 899,
      stock: 60,
      imageUrl: 'https://loremflickr.com/800/800/tiffin,lunchbox?lock=63',
    },
    {
      name: 'Sheesham Wood Chakla and Belan Set',
      description: 'Solid rosewood rolling board and pin, smooth and sturdy for making rotis and parathas.',
      price: 699,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/rolling,pin?lock=64',
    },
    {
      name: 'Granite Mortar and Pestle',
      description: 'Heavy stone mortar and pestle for grinding spices and pastes, with a rough interior that crushes efficiently.',
      price: 999,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/mortar,pestle?lock=65',
    },
    {
      name: 'Brass Masala Dabba with 7 Bowls',
      description: 'Round spice box with seven small bowls and a spoon, with a domed lid to keep spices fresh.',
      price: 1499,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/spice,box?lock=66',
    },
    {
      name: 'Sheesham Wood Serving Spoon Set of 5',
      description: 'Hand-carved spoons and ladles with smooth finishes, gentle on non-stick and delicate cookware.',
      price: 499,
      stock: 80,
      imageUrl: 'https://loremflickr.com/800/800/wooden,spoons?lock=67',
    },
    {
      name: 'Cast Iron Dosa Tawa 12-inch',
      description: 'Flat, pre-seasoned griddle with a long handle, giving crisp golden dosas and uttapams.',
      price: 1299,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/dosa,tawa?lock=68',
    },
    {
      name: 'Bamboo Chopping Board',
      description: 'Large, knife-friendly board with a juice groove, made from sustainably grown bamboo.',
      price: 599,
      stock: 55,
      imageUrl: 'https://loremflickr.com/800/800/chopping,board?lock=69',
    },
    {
      name: 'Copper Bottom Steel Saucepan',
      description: 'Stainless steel saucepan with a copper base for fast, even heating. 1.5 litre capacity with a lid.',
      price: 1399,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/steel,saucepan?lock=70',
    },
    {
      name: 'Kansa Bell Metal Thali Set',
      description: 'Traditional plate and bowls in kansa, valued in Ayurveda for eating and known for its long life.',
      price: 2999,
      stock: 15,
      imageUrl: 'https://loremflickr.com/800/800/brass,thali?lock=71',
    },
    {
      name: 'Cane Roti Basket with Cloth Liner',
      description: 'Handwoven cane basket with a cotton lining that keeps rotis warm and soft at the table.',
      price: 349,
      stock: 50,
      imageUrl: 'https://loremflickr.com/800/800/cane,basket?lock=72',
    },
    {
      name: 'Stainless Steel Idli Steamer',
      description: 'Four-plate steamer with a sturdy lid, making 16 idlis at a time. Works on gas and induction.',
      price: 1099,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/idli,steamer?lock=73',
    },
    {
      name: 'Clay Handi Cooking Pot with Lid',
      description: 'Unglazed earthen pot for slow cooking, giving dal and biryani a distinct earthy flavour.',
      price: 899,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/clay,pot?lock=74',
    },
    {
      name: 'Pure Copper Tumbler Set of 2',
      description: 'Plain copper tumblers with a smooth finish, traditionally used for drinking water stored overnight.',
      price: 799,
      stock: 50,
      imageUrl: 'https://loremflickr.com/800/800/copper,tumbler?lock=75',
    },
    {
      name: 'Jute-Wrapped Glass Storage Jars Set of 3',
      description: 'Airtight glass jars with bamboo lids and a natural jute wrap, in three sizes for pantry staples.',
      price: 899,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/glass,jars?lock=76',
    },
    {
      name: 'Acacia Wood Serving Board',
      description: 'Rustic serving board with a live edge and a hanging hole, great for cheese, fruit and snacks.',
      price: 1199,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/serving,board?lock=77',
    },
    {
      name: 'Stainless Steel Airtight Container Set of 4',
      description: 'Four kitchen canisters in graduated sizes with silicone-sealed lids that keep contents dry.',
      price: 1299,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/steel,containers?lock=78',
    },
    {
      name: 'Brass Urli Serving Bowl',
      description: 'Wide, shallow serving bowl in polished brass, traditionally used to display floating flowers and candles.',
      price: 2199,
      stock: 12,
      imageUrl: 'https://loremflickr.com/800/800/brass,bowl?lock=79',
    },
    {
      name: 'Neem Wood Spatula Set',
      description: 'Set of 3 turners and a spoon in naturally antibacterial neem wood, gentle on pans.',
      price: 399,
      stock: 70,
      imageUrl: 'https://loremflickr.com/800/800/wooden,spatula?lock=80',
    },
  ],
  Lighting: [
    {
      name: 'Brass Diya Lamp Set of 4',
      description: 'Four polished brass oil lamps with a classic lotus base, used for festivals and daily pujas.',
      price: 799,
      stock: 60,
      imageUrl: 'https://loremflickr.com/800/800/brass,diya?lock=81',
    },
    {
      name: 'Rattan Pendant Lamp Shade',
      description: 'Handwoven rattan shade that casts warm patterned light, fits standard E27 fittings. 40 cm wide.',
      price: 2299,
      stock: 20,
      imageUrl: 'https://loremflickr.com/800/800/rattan,pendant?lock=82',
    },
    {
      name: 'Hand-Punched Iron Lantern',
      description: 'Tabletop lantern with hand-punched patterns that throw star-like light across a room.',
      price: 1299,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/iron,lantern?lock=83',
    },
    {
      name: 'Terracotta Tea-Light Holder Set of 3',
      description: 'Three small clay holders with cut-out designs that glow warmly when lit. Suitable for tea lights.',
      price: 499,
      stock: 70,
      imageUrl: 'https://loremflickr.com/800/800/terracotta,candle?lock=84',
    },
    {
      name: 'Jute Woven Table Lamp',
      description: 'Table lamp with a woven jute shade and a solid wood base, giving a soft natural glow.',
      price: 1799,
      stock: 22,
      imageUrl: 'https://loremflickr.com/800/800/jute,lamp?lock=85',
    },
    {
      name: 'Traditional Brass Samai Oil Lamp',
      description: 'Classic South Indian standing lamp with a decorative peacock on the handle, used for daily worship.',
      price: 999,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/brass,lamp?lock=86',
    },
    {
      name: 'Bamboo Pendant Light',
      description: 'Airy pendant shade woven from split bamboo by artisans in Assam, ideal for dining and living rooms.',
      price: 2499,
      stock: 15,
      imageUrl: 'https://loremflickr.com/800/800/bamboo,lamp?lock=87',
    },
    {
      name: 'Glass Hurricane Lantern',
      description: 'Tall clear-glass lantern with a metal handle and a removable base, for candles indoors or outdoors.',
      price: 1099,
      stock: 28,
      imageUrl: 'https://loremflickr.com/800/800/hurricane,lantern?lock=88',
    },
    {
      name: 'Handmade Paper Lantern Set of 3',
      description: 'Foldable lanterns in soft cotton paper with warm LED fairy-light inserts included.',
      price: 699,
      stock: 50,
      imageUrl: 'https://loremflickr.com/800/800/paper,lantern?lock=89',
    },
    {
      name: 'Wooden Floor Lamp with Linen Shade',
      description: 'Tripod floor lamp in natural wood with an off-white linen shade for reading corners.',
      price: 3999,
      stock: 10,
      imageUrl: 'https://loremflickr.com/800/800/floor,lamp?lock=90',
    },
    {
      name: 'Macrame Pendant Light Cover',
      description: 'Hand-knotted cotton macrame cover to dress up a plain hanging bulb holder.',
      price: 1499,
      stock: 25,
      imageUrl: 'https://loremflickr.com/800/800/macrame,pendant?lock=91',
    },
    {
      name: 'Wrought Iron Candle Stand',
      description: 'Three-arm candle stand hand-forged from iron with a matte black finish. 30 cm tall.',
      price: 1199,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/candle,stand?lock=92',
    },
    {
      name: 'Hand-Poured Sandalwood Soy Candle',
      description: 'Slow-burning soy wax candle scented with sandalwood oil, poured into a reusable glass jar.',
      price: 549,
      stock: 90,
      imageUrl: 'https://loremflickr.com/800/800/soy,candle?lock=93',
    },
    {
      name: 'Copper Wire Fairy String Lights',
      description: 'Ten-metre string of warm-white micro LEDs on flexible copper wire, battery powered.',
      price: 399,
      stock: 100,
      imageUrl: 'https://loremflickr.com/800/800/fairy,lights?lock=94',
    },
    {
      name: 'Recycled Glass Bottle Table Lamp',
      description: 'Table lamp made from a hand-cut recycled bottle, with a brass fitting and a cotton cord.',
      price: 1699,
      stock: 20,
      imageUrl: 'https://loremflickr.com/800/800/bottle,lamp?lock=95',
    },
    {
      name: 'Capiz Shell Chandelier',
      description: 'Pendant chandelier of layered capiz shells that shimmer softly when lit. 50 cm diameter.',
      price: 5499,
      stock: 8,
      imageUrl: 'https://loremflickr.com/800/800/chandelier,shell?lock=96',
    },
    {
      name: 'Hand-Carved Wooden Table Lamp',
      description: 'Mango wood lamp carved with a floral lattice and finished in a warm honey tone.',
      price: 2199,
      stock: 18,
      imageUrl: 'https://loremflickr.com/800/800/wooden,lamp?lock=97',
    },
    {
      name: 'Pierced Brass Hanging Lantern',
      description: 'Ornate hanging lantern with intricate pierced patterns for porches and balconies.',
      price: 1899,
      stock: 20,
      imageUrl: 'https://loremflickr.com/800/800/hanging,lantern?lock=98',
    },
    {
      name: 'Scented Beeswax Pillar Candle Set',
      description: 'Three natural beeswax pillar candles in different sizes with a subtle honey scent.',
      price: 799,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/beeswax,candle?lock=99',
    },
    {
      name: 'Ceramic Base Bedside Lamp',
      description: 'Compact lamp with a hand-glazed ceramic base and a fabric drum shade, ideal for bedside tables.',
      price: 1999,
      stock: 24,
      imageUrl: 'https://loremflickr.com/800/800/bedside,lamp?lock=100',
    },
  ],
  Stationery: [
    {
      name: 'Handmade Cotton Rag Paper Notebook A5',
      description: 'Hand-stitched notebook made from recycled cotton rag paper with a natural deckle edge. 120 pages.',
      price: 349,
      stock: 100,
      imageUrl: 'https://loremflickr.com/800/800/notebook,paper?lock=101',
    },
    {
      name: 'Leather-Bound Journal',
      description: 'Genuine leather journal with a wrap-around strap and thick unlined pages, ages beautifully with use.',
      price: 899,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/leather,journal?lock=102',
    },
    {
      name: 'Plantable Seed Paper Greeting Cards Set of 10',
      description: 'Greeting cards that can be planted to grow wildflowers. Comes with blank envelopes.',
      price: 449,
      stock: 60,
      imageUrl: 'https://loremflickr.com/800/800/greeting,cards?lock=103',
    },
    {
      name: 'Handmade Paper Envelopes Set of 20',
      description: 'Envelopes in mixed pastel colours made from handmade cotton paper, C6 size.',
      price: 299,
      stock: 80,
      imageUrl: 'https://loremflickr.com/800/800/paper,envelopes?lock=104',
    },
    {
      name: 'Brass Fountain Pen',
      description: 'Weighty brass pen with a smooth steel nib and a screw-on cap, includes a converter and two ink cartridges.',
      price: 1499,
      stock: 30,
      imageUrl: 'https://loremflickr.com/800/800/fountain,pen?lock=105',
    },
    {
      name: 'Recycled Newspaper Pencils Set of 20',
      description: 'Pencils wrapped from old newspapers, with graphite cores and a natural finish. Eco-friendly and sharpener-friendly.',
      price: 199,
      stock: 120,
      imageUrl: 'https://loremflickr.com/800/800/pencils,colored?lock=106',
    },
    {
      name: 'Wax Seal Stamp Kit',
      description: 'Kit with brass seal stamp, three wax sticks and a spoon, for letters and gift wrapping.',
      price: 699,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/wax,seal?lock=107',
    },
    {
      name: 'Bamboo Desk Organiser',
      description: 'Multi-compartment organiser for pens, notes and phone, made from sustainably harvested bamboo.',
      price: 799,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/desk,organizer?lock=108',
    },
    {
      name: 'Hand-Bound Sketchbook A4',
      description: 'Thick-paged sketchbook with a linen cover, suitable for pencil, ink and light washes.',
      price: 549,
      stock: 55,
      imageUrl: 'https://loremflickr.com/800/800/sketchbook,drawing?lock=109',
    },
    {
      name: 'Calligraphy Dip Pen Set',
      description: 'Wooden pen holder with five nibs and two ink bottles, perfect for lettering practice.',
      price: 999,
      stock: 25,
      imageUrl: 'https://loremflickr.com/800/800/calligraphy,pen?lock=110',
    },
    {
      name: 'Recycled Paper Weekly Planner',
      description: 'Undated planner with a weekly layout, goal pages and a kraft cover, made with post-consumer paper.',
      price: 399,
      stock: 70,
      imageUrl: 'https://loremflickr.com/800/800/planner,notebook?lock=111',
    },
    {
      name: 'Block-Printed Gift Wrap Paper Set of 5',
      description: 'Five large sheets of handmade paper hand-printed with traditional blocks in vibrant colours.',
      price: 349,
      stock: 65,
      imageUrl: 'https://loremflickr.com/800/800/gift,wrap?lock=112',
    },
    {
      name: 'Terracotta Pen Stand',
      description: 'Hand-painted clay pen holder with a warm terracotta finish, sized for a standard desk.',
      price: 349,
      stock: 60,
      imageUrl: 'https://loremflickr.com/800/800/pen,holder?lock=113',
    },
    {
      name: 'Brass Bookmark Set of 6',
      description: 'Six slim brass bookmarks with cut-out patterns of leaves, birds and lotus, on a gift card.',
      price: 399,
      stock: 80,
      imageUrl: 'https://loremflickr.com/800/800/bookmark,brass?lock=114',
    },
    {
      name: 'Lokta Paper Diary',
      description: 'Hand-bound diary with a durable lokta paper cover and thick, ink-friendly pages.',
      price: 599,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/paper,diary?lock=115',
    },
    {
      name: 'Watercolour Paper Pad A4',
      description: 'Cold-pressed cotton paper pad that takes washes without warping. 20 sheets, 300 gsm.',
      price: 499,
      stock: 50,
      imageUrl: 'https://loremflickr.com/800/800/watercolor,paper?lock=116',
    },
    {
      name: 'Madhubani Print Notecards Set of 8',
      description: 'Notecards printed with folk art from Bihar, with matching envelopes in a keepsake box.',
      price: 449,
      stock: 55,
      imageUrl: 'https://loremflickr.com/800/800/madhubani,art?lock=117',
    },
    {
      name: 'Hand-Carved Wooden Stamp Set',
      description: 'Set of 6 wooden stamps carved with nature motifs, with an ink pad for cards and journals.',
      price: 649,
      stock: 40,
      imageUrl: 'https://loremflickr.com/800/800/wooden,stamps?lock=118',
    },
    {
      name: 'Leather Passport Holder and Cardholder',
      description: 'Slim leather cover with card slots and an elastic pen loop, in a vegetable-tanned finish.',
      price: 799,
      stock: 35,
      imageUrl: 'https://loremflickr.com/800/800/leather,wallet?lock=119',
    },
    {
      name: 'Cloth-Bound Pocket Notebook Set of 3',
      description: 'Three pocket notebooks with block-printed cloth covers and dotted pages.',
      price: 699,
      stock: 45,
      imageUrl: 'https://loremflickr.com/800/800/pocket,notebook?lock=120',
    },
  ],
};

// Flat list with a category field added, handy for bulk inserts.
export const allProducts = Object.entries(productsByCategory).flatMap(([category, items]) =>
  items.map((item) => ({ ...item, category }))
);
